import os from 'os';
import path from 'path';
import { FileNode, CleanupSuggestionGroup, CleanupSuggestionItem } from '../models/types';
import { CompiledIgnore, matchesAny } from '../utils/glob';

/**
 * cleanupRules — well-known reclaimable disk space, matched against a
 * completed scan tree (so suggestions always sit inside a scanned root and
 * flow through the same trash-only delete path as everything else).
 *
 * Two kinds of rules:
 *  - name rules: directory/file basenames (node_modules, .DS_Store, …)
 *  - path rules: absolute OS-specific locations (browser caches, Xcode, …)
 *
 * A directory claimed by a rule is reported once and not descended into, so
 * a nested node_modules never produces overlapping suggestions.
 */

const ITEMS_PER_RULE = 200;
/** Files in Downloads older than this count as stale. */
const OLD_DOWNLOAD_DAYS = 90;
const OLD_DOWNLOAD_MIN_SIZE = 1_048_576; // 1 MB — skip noise

interface NameRule {
  id: string;
  title: string;
  description: string;
  type: 'dir' | 'file';
  names: Set<string>;
}

const NAME_RULES: NameRule[] = [
  {
    id: 'node-modules',
    title: 'node_modules',
    description: 'JavaScript dependencies — safe to trash, reinstall with npm install',
    type: 'dir',
    names: new Set(['node_modules']),
  },
  {
    id: 'build-output',
    title: 'Build output',
    description: 'Compiled output folders — regenerated by the next build',
    type: 'dir',
    names: new Set(['dist', '.next', '.nuxt', '.output', 'target', '.svelte-kit', '.angular']),
  },
  {
    id: 'tool-caches',
    title: 'Tool caches',
    description: 'Caches left by dev tools — rebuilt automatically when needed',
    type: 'dir',
    names: new Set(['__pycache__', '.pytest_cache', '.mypy_cache', '.gradle', '.turbo', '.parcel-cache', '.eslintcache', 'coverage', '.venv', '.tox']),
  },
  {
    id: 'os-junk',
    title: 'OS junk files',
    description: 'Hidden metadata files the OS recreates on demand',
    type: 'file',
    names: new Set(['.ds_store', 'thumbs.db', 'desktop.ini']),
  },
];

/** Absolute, OS-specific cache locations (matched as path prefixes). */
function pathRules(): { id: string; title: string; description: string; prefixes: string[] }[] {
  const home = os.homedir();
  const j = (...parts: string[]) => path.join(...parts);

  if (process.platform === 'darwin') {
    return [
      {
        id: 'browser-caches',
        title: 'Browser caches',
        description: 'Chrome / Safari / Firefox caches — pages reload a bit slower once',
        prefixes: [
          j(home, 'Library', 'Caches', 'Google', 'Chrome'),
          j(home, 'Library', 'Caches', 'com.apple.Safari'),
          j(home, 'Library', 'Caches', 'Firefox'),
          j(home, 'Library', 'Caches', 'Chromium'),
          j(home, 'Library', 'Caches', 'company.thebrowser.Browser'),
        ],
      },
      {
        id: 'dev-caches',
        title: 'Developer caches',
        description: 'Xcode and package-manager caches — rebuilt when next used',
        prefixes: [
          j(home, 'Library', 'Developer', 'Xcode', 'DerivedData'),
          j(home, 'Library', 'Developer', 'Xcode', 'iOS DeviceSupport'),
          j(home, 'Library', 'Developer', 'CoreSimulator', 'Caches'),
          j(home, 'Library', 'Caches', 'Homebrew'),
          j(home, 'Library', 'Caches', 'pip'),
          j(home, 'Library', 'Caches', 'Yarn'),
          j(home, '.npm', '_cacache'),
        ],
      },
    ];
  }
  if (process.platform === 'win32') {
    const local = process.env.LOCALAPPDATA || j(home, 'AppData', 'Local');
    return [
      {
        id: 'browser-caches',
        title: 'Browser caches',
        description: 'Chrome / Edge / Firefox caches — pages reload a bit slower once',
        prefixes: [
          j(local, 'Google', 'Chrome', 'User Data', 'Default', 'Cache'),
          j(local, 'Microsoft', 'Edge', 'User Data', 'Default', 'Cache'),
          j(local, 'Mozilla', 'Firefox', 'Profiles'),
        ],
      },
      {
        id: 'dev-caches',
        title: 'Developer caches',
        description: 'Package-manager and tool caches — rebuilt when next used',
        prefixes: [
          j(local, 'npm-cache'),
          j(local, 'Yarn', 'Cache'),
          j(local, 'pip', 'cache'),
          j(local, 'NuGet', 'Cache'),
          j(local, 'Temp'),
        ],
      },
    ];
  }
  return [
    {
      id: 'browser-caches',
      title: 'Browser caches',
      description: 'Chrome / Firefox caches — pages reload a bit slower once',
      prefixes: [
        j(home, '.cache', 'google-chrome'),
        j(home, '.cache', 'chromium'),
        j(home, '.cache', 'mozilla'),
      ],
    },
    {
      id: 'dev-caches',
      title: 'Developer caches',
      description: 'Package-manager and tool caches — rebuilt when next used',
      prefixes: [
        j(home, '.npm', '_cacache'),
        j(home, '.cache', 'yarn'),
        j(home, '.cache', 'pip'),
      ],
    },
  ];
}

function samePath(a: string, b: string): boolean {
  return process.platform === 'linux' ? a === b : a.toLowerCase() === b.toLowerCase();
}

export function collectCleanupSuggestions(root: FileNode, ignore: CompiledIgnore[]): CleanupSuggestionGroup[] {
  const downloadsDir = path.join(os.homedir(), 'Downloads');
  const oldDownloadCutoff = Date.now() - OLD_DOWNLOAD_DAYS * 86_400_000;
  const prefixRules = pathRules();

  const groups = new Map<string, CleanupSuggestionGroup>();
  const add = (id: string, title: string, description: string, node: FileNode): void => {
    let group = groups.get(id);
    if (!group) {
      group = { id, title, description, items: [], totalSize: 0 };
      groups.set(id, group);
    }
    group.totalSize += node.size;
    if (group.items.length < ITEMS_PER_RULE) {
      group.items.push({
        name: node.name,
        path: node.path,
        size: node.size,
        type: node.type,
        modifiedAt: node.modifiedAt,
      } satisfies CleanupSuggestionItem);
    }
  };

  const visit = (node: FileNode): void => {
    if (!node.children) return;
    for (const child of node.children) {
      if (matchesAny(ignore, child.path, child.name)) continue; // user said hands off

      if (child.type === 'dir') {
        const lower = child.name.toLowerCase();
        const nameRule = NAME_RULES.find((r) => r.type === 'dir' && r.names.has(lower));
        if (nameRule && child.size > 0) {
          add(nameRule.id, nameRule.title, nameRule.description, child);
          continue; // claimed — don't descend
        }
        const prefixRule = prefixRules.find((r) => r.prefixes.some((p) => samePath(p, child.path)));
        if (prefixRule && child.size > 0) {
          add(prefixRule.id, prefixRule.title, prefixRule.description, child);
          continue;
        }
        visit(child);
        continue;
      }

      const lower = child.name.toLowerCase();
      const fileRule = NAME_RULES.find((r) => r.type === 'file' && r.names.has(lower));
      if (fileRule) {
        add(fileRule.id, fileRule.title, fileRule.description, child);
        continue;
      }
      if (
        child.size >= OLD_DOWNLOAD_MIN_SIZE &&
        child.modifiedAt < oldDownloadCutoff &&
        (child.path.startsWith(downloadsDir + path.sep) || samePath(path.dirname(child.path), downloadsDir))
      ) {
        add(
          'old-downloads',
          'Old Downloads',
          `Files in Downloads untouched for ${OLD_DOWNLOAD_DAYS}+ days`,
          child
        );
      }
    }
  };
  visit(root);

  return [...groups.values()]
    .map((g) => ({ ...g, items: g.items.sort((a, b) => b.size - a.size) }))
    .sort((a, b) => b.totalSize - a.totalSize);
}
