import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

import { isolatedDataDir } from './fixtures/dataDir';
isolatedDataDir('treemap-cloud-rules-data-');

import { CLOUD_RULES, cloudMatchers, cloudProviderFor, firstMatchingProvider } from '../src/services/cloudFolders';
import { Flag, PackedScanStore } from '../src/services/scanStore';
import {
  EDGE_CASES, ORACLE_GENERATED, ORACLE_PATH, PROVIDER_ID, decodeLikeNode, escapeBytes, generatedPaths,
  oldCloudProviderFor, oracleText, parseOracle, productionRules, randomCodeUnitStrings, referenceMatcher, unescapeBytes, utf8,
} from './fixtures/cloudRulesOracle';

/**
 * The cloud gate as one table (decision P4-3a, Phase 4 task T11): the regexes
 * `cloudProviderFor` asks are built from `CLOUD_RULES`, and tm-store's Rust
 * matcher (`derive::cloud_provider`) answers the same rows, for the storage
 * modes that are to decide the rule during the walk. Both must answer
 * exactly as the regexes did before the table — held here against a frozen
 * copy of them (`oldCloudProviderFor`) on hand-picked edge cases and 300,000
 * generated paths and random strings, and in Rust against the committed
 * oracle this file keeps current (`native/treemap-core/crates/tm-store/tests/cloud.rs`).
 *
 * The Rust matcher compares ASCII letters ignoring case and nothing else. That
 * is the regexes' rule because their `i` flag comes without `u`: the spec's
 * Canonicalize upper-cases a character, but never maps one outside ASCII onto
 * one inside it, so U+212A KELVIN SIGN is not `k`, U+0130 is not `i` and
 * U+017F is not `s`. The sets that rule depends on are pinned below over every
 * code point, and were measured identical in Node 24.16.0 (Unicode 17.0, ICU
 * 78.3) and in the app's Electron 31.7.7, whose Node is 20.18.0 (Unicode 15.1,
 * ICU 74.2), run as Node with ELECTRON_RUN_AS_NODE=1 on 25 Sep 2026: this
 * whole file passed there too, its oracle regenerated byte for byte.
 */

const hex = (cp: number): string => `U+${cp.toString(16).toUpperCase().padStart(4, '0')}`;
const idOf = (provider: keyof typeof PROVIDER_ID | undefined): number => (provider ? PROVIDER_ID[provider] : 0);

test('the table builds the regexes it replaced, character for character', () => {
  const old: Array<[string, RegExp]> = [
    ['icloud', /Library\/Mobile Documents|com~apple~CloudDocs|\.icloud$/i],
    ['onedrive', /OneDrive/i],
    ['dropbox', /Dropbox/i],
  ];
  assert.deepEqual(
    cloudMatchers(CLOUD_RULES).map(({ provider, regex }) => [provider, regex.source, regex.flags]),
    old.map(([provider, regex]) => [provider, regex.source, regex.flags]),
  );
  assert.ok(Object.isFrozen(CLOUD_RULES) && CLOUD_RULES.every((rule) => Object.isFrozen(rule)), 'the table cannot drift from the regexes built at load');
});

test('cloudProviderFor answers each hand-picked edge case as the old regexes did', () => {
  for (const edge of EDGE_CASES) {
    const text = typeof edge.path === 'string' ? edge.path : decodeLikeNode(edge.path);
    assert.equal(oldCloudProviderFor(text), edge.expected, `the old regexes: ${edge.why}`);
    assert.equal(cloudProviderFor(text), edge.expected, edge.why);
    if (typeof edge.path === 'string') {
      assert.equal(cloudProviderFor(decodeLikeNode(utf8(edge.path))), edge.expected, `${edge.why}, through UTF-8`);
    }
  }
});

test('cloudProviderFor answers as the old regexes on 200,000 generated paths and 100,000 random strings', () => {
  const tally = { icloud: 0, onedrive: 0, dropbox: 0, none: 0 };
  const misses: string[] = [];
  let checked = 0;
  const check = (p: string): void => {
    const want = oldCloudProviderFor(p);
    const got = cloudProviderFor(p);
    if (got !== want && misses.length < 10) misses.push(`${JSON.stringify(p)}: ${got} where the old regexes said ${want}`);
    tally[want ?? 'none']++;
    checked++;
  };
  for (const p of generatedPaths(4_2026_09_25, 200_000)) {
    if (typeof p === 'string') {
      check(p);
      if (/[\uD800-\uDFFF]/.test(p)) check(decodeLikeNode(utf8(p)));
    } else {
      check(decodeLikeNode(p));
    }
  }
  for (const s of randomCodeUnitStrings(9_2026_09_25, 100_000)) check(s);
  assert.deepEqual(misses, []);
  assert.ok(checked >= 300_000, `${checked} checked`);
  for (const [answer, count] of Object.entries(tally)) {
    assert.ok(count >= 10_000, `the old regexes gave ${answer} ${count} times: too few for the comparison to mean much`);
  }
});

test('cloudProviderFor keeps nothing between calls', () => {
  for (let k = 0; k < 3; k++) {
    assert.equal(cloudProviderFor('/Users/me/OneDrive/a'), 'onedrive');
    assert.equal(cloudProviderFor('/Users/me/OneDrive/b'), 'onedrive');
    assert.equal(cloudProviderFor('/Users/me/x.icloud'), 'icloud');
    assert.equal(cloudProviderFor('/Users/me/x'), undefined);
  }
});

test('the committed oracle is what the regexes answer today', () => {
  const committed = fs.readFileSync(ORACLE_PATH, 'utf8');
  const today = oracleText();
  assert.ok(
    committed === today,
    `the oracle is stale: regenerate it with \`npx tsx tests/fixtures/cloudRulesOracle.ts\` and commit it (${committed.length} bytes committed, ${today.length} today)`,
  );
});

test('the oracle holds CLOUD_RULES, every edge case and tens of thousands of paths, and every table answers through the builder as the regexes do', () => {
  const tables = parseOracle(fs.readFileSync(ORACLE_PATH, 'utf8'));
  assert.deepEqual(tables.map((t) => t.name), ['cloudProviderFor', 'probe-letters', 'probe-ends', 'probe-order', 'probe-syntax', 'probe-ligatures']);
  const [production] = tables;
  assert.deepEqual(production.rules, productionRules());
  assert.equal(production.paths.length, EDGE_CASES.length + ORACLE_GENERATED);
  assert.ok(ORACLE_GENERATED >= 20_000);

  EDGE_CASES.forEach((edge, k) => {
    const bytes = typeof edge.path === 'string' ? utf8(edge.path) : edge.path;
    assert.deepEqual(production.paths[k], bytes, edge.why);
    assert.equal(production.expected[k], idOf(edge.expected), edge.why);
  });
  const counts = new Map<number, number>();
  for (const id of production.expected) counts.set(id, (counts.get(id) ?? 0) + 1);
  for (const id of [0, 1, 2, 3]) assert.ok((counts.get(id) ?? 0) >= 1_000, `provider ${id}: ${counts.get(id) ?? 0} paths`);
  const notUtf8 = production.paths.filter((bytes) => !Buffer.from(decodeLikeNode(bytes), 'utf8').equals(Buffer.from(bytes))).length;
  assert.ok(notUtf8 >= 1_000, `${notUtf8} paths are not UTF-8`);

  let checked = 0;
  for (const table of tables) {
    const matchers = cloudMatchers(table.rules);
    const reference = referenceMatcher(table.rules);
    table.paths.forEach((bytes, k) => {
      const text = decodeLikeNode(bytes);
      const where = `${table.name} ${JSON.stringify(text)}`;
      assert.equal(firstMatchingProvider(matchers, text) ?? 0, table.expected[k], where);
      assert.equal(reference(text), table.expected[k], `the reference, ${where}`);
      checked++;
    });
  }
  production.paths.forEach((bytes, k) => {
    assert.equal(idOf(cloudProviderFor(decodeLikeNode(bytes))), production.expected[k], JSON.stringify(decodeLikeNode(bytes)));
  });
  assert.ok(tables.every((t) => t.rules.length > 0 && t.paths.length > 0), 'no table is empty');
  assert.ok(tables[1].paths.length >= 3_000, `${tables[1].paths.length} paths try the letters`);
  assert.equal(checked, tables.reduce((sum, t) => sum + t.paths.length, 0));
});

test('the probes answer as written by hand where a matcher could go wrong', () => {
  const tables = new Map(parseOracle(fs.readFileSync(ORACLE_PATH, 'utf8')).map((t) => [t.name, t]));
  const answer = (name: string, path: string): number => {
    const table = tables.get(name);
    assert.ok(table, name);
    const k = table.paths.findIndex((bytes) => Buffer.from(bytes).equals(Buffer.from(utf8(path))));
    assert.ok(k >= 0, `${name} holds ${JSON.stringify(path)}`);
    return table.expected[k];
  };
  // Every ASCII letter is its own provider: K is 11, i 9, s 19.
  assert.equal(answer('probe-letters', 'K'), 11);
  assert.equal(answer('probe-letters', 'k'), 11);
  assert.equal(answer('probe-letters', '\u212A'), 0, 'KELVIN SIGN is not k');
  assert.equal(answer('probe-letters', '\u0130'), 0, 'U+0130 is not i');
  assert.equal(answer('probe-letters', '\u0131'), 0, 'U+0131 is not i');
  assert.equal(answer('probe-letters', '\u017F'), 0, 'U+017F is not s');
  assert.equal(answer('probe-letters', '\uFF4B'), 0, 'a fullwidth k is not k');
  assert.equal(answer('probe-ends', 'xK'), 1);
  assert.equal(answer('probe-ends', 'x\u212A'), 0);
  assert.equal(answer('probe-ends', 'xk\n'), 0, 'not before a final newline');
  assert.equal(answer('probe-ends', 'kx'), 0, 'an end rule is not an anywhere rule');
  assert.equal(answer('probe-ends', 'ax'), 0, 'a dot is a dot');
  assert.equal(answer('probe-order', 'ba'), 2, 'the first rule wins');
  assert.equal(answer('probe-order', 'axc'), 3, 'the first rule wins, not the first rule of the provider');
  assert.equal(answer('probe-order', 'ca'), 1);
  assert.equal(answer('probe-syntax', 'abc'), 0, 'the dot in a.c is a dot');
  assert.equal(answer('probe-syntax', 'u'), 0, 'the bar in u|v is a bar');
  assert.equal(answer('probe-syntax', 'z1'), 0, 'the backslash in z\\d is a backslash');
  assert.equal(answer('probe-ligatures', '\u00DF'), 0, '\u00DF is not ss');
  assert.equal(answer('probe-ligatures', '\uFB06'), 0, 'the st ligature is not st');
});

test("JavaScript's i flag without u never takes a character outside ASCII for one inside it, over every code point", () => {
  const anyAscii = /[\0-\x7f]/i;
  const anyAsciiUnicode = /[\0-\x7f]/iu;
  const folded: string[] = [];
  const foldedWithU: string[] = [];
  for (let cp = 0x80; cp <= 0x10ffff; cp++) {
    const s = String.fromCodePoint(cp); // a lone surrogate for U+D800-U+DFFF, as a JavaScript string may hold
    if (anyAscii.test(s)) folded.push(hex(cp));
    if ((cp < 0xd800 || cp > 0xdfff) && anyAsciiUnicode.test(s)) foldedWithU.push(hex(cp));
  }
  assert.deepEqual(folded, []);
  assert.deepEqual(foldedWithU, ['U+017F', 'U+212A'], 'the u flag would fold these onto s and k: never add it');
  assert.equal(/k/i.test('\u212A'), false);
  assert.equal(/i/i.test('\u0130'), false);
  assert.equal(/i/i.test('\u0131'), false);
  assert.equal(/s/i.test('\u017F'), false);
  assert.equal(/k/iu.test('\u212A'), true);
  assert.equal(/s/iu.test('\u017F'), true);
});

test('the code points whose JavaScript lower or upper case holds ASCII are pinned (Node 24.16 and Electron 31 agree)', () => {
  const lower: string[] = [];
  const upper: string[] = [];
  const holdsAscii = (s: string): boolean => /[\0-\x7f]/.test(s);
  for (let cp = 0x80; cp <= 0x10ffff; cp++) {
    if (cp >= 0xd800 && cp <= 0xdfff) continue;
    const s = String.fromCodePoint(cp);
    if (holdsAscii(s.toLowerCase())) lower.push(hex(cp));
    if (holdsAscii(s.toUpperCase())) upper.push(hex(cp));
  }
  assert.deepEqual(lower, ['U+0130', 'U+212A']);
  assert.deepEqual(upper, [
    'U+00DF', 'U+0131', 'U+0149', 'U+017F', 'U+01F0', 'U+1E96', 'U+1E97', 'U+1E98', 'U+1E99', 'U+1E9A',
    'U+FB00', 'U+FB01', 'U+FB02', 'U+FB03', 'U+FB04', 'U+FB05', 'U+FB06',
  ]);
  // So a table matched through toLowerCase() would take U+0130 for i and U+212A for k; the regexes do not.
  for (const [c, letter] of [['\u0130', 'i'], ['\u212A', 'k']]) {
    assert.ok(c.toLowerCase().includes(letter), `${hex(c.charCodeAt(0))} lower-cases to hold ${letter}`);
    assert.equal(new RegExp(letter, 'i').test(c), false, `the regex does not take ${hex(c.charCodeAt(0))} for ${letter}`);
  }
});

test("the oracle's provider numbers are the store's own cloud column", () => {
  const store = new PackedScanStore('/r', '/', { name: 'r', isDir: true, size: 0, modifiedAt: 0, isHidden: false });
  const n = 4;
  store.adoptColumns({
    n,
    capacity: n,
    parent: Int32Array.from([-1, 0, 0, 0]),
    size: new Float64Array(n),
    mtime: new Float64Array(n),
    atime: null,
    flags: Uint16Array.from([Flag.Dir | Flag.HasChildArray, 0, 0, 0]),
    ext: new Uint16Array(n),
    container: new Uint8Array(n),
    cloudProv: Uint8Array.from([0, PROVIDER_ID.icloud, PROVIDER_ID.onedrive, PROVIDER_ID.dropbox]),
    nameOff: Uint32Array.from([0, 1, 2, 3, 4]),
    names: new TextEncoder().encode('rabc'),
    namesLen: 4,
    childStart: Uint32Array.from([1, 4, 4, 4]),
    childCnt: Uint32Array.from([3, 0, 0, 0]),
    extDict: [''],
    extOverflow: [],
  });
  assert.deepEqual([0, 1, 2, 3].map((id) => store.cloudProvider(id)), [undefined, 'icloud', 'onedrive', 'dropbox']);
});

test('a table the Rust matcher could not answer as the regexes do is refused', () => {
  // Outside ASCII the i flag folds letters among themselves, which a matcher of ASCII case could not follow.
  assert.equal(/\u00E9/i.test('\u00C9'), true);
  for (const text of ['Caf\u00E9', '', 'a\tb', 'a\nb', '\u212A', 'x\u007F']) {
    assert.throws(() => cloudMatchers([{ provider: 'icloud', text, at: 'anywhere' }]), /printable ASCII/, JSON.stringify(text));
  }
  assert.throws(() => cloudMatchers([{ provider: 'icloud', text: 'x', at: 'start' as never }]), /anywhere or end/);
  assert.doesNotThrow(() => cloudMatchers([{ provider: 'icloud', text: ' ~!"#$%&\'()*+,-./09:;<=>?@AZ[\\]^_`az{|}', at: 'end' }]));
});

test('the oracle file escapes what a tab-separated line cannot hold, and reads back byte for byte', () => {
  const bytes = new Uint8Array([0x41, 0x09, 0x0a, 0x25, 0x20, 0x7f, 0x80, 0xff, 0x20]);
  assert.equal(escapeBytes(bytes), 'A%09%0A%25 %7F%80%FF%20');
  assert.deepEqual(unescapeBytes(escapeBytes(bytes)), bytes);
  assert.throws(() => unescapeBytes('%G1'), /bad escape/);
  assert.throws(() => unescapeBytes('a%4'), /bad escape/);
});
