/**
 * The webview document that frames the running visualizer.
 *
 * Pure: builds a string. No `vscode`. The Content-Security-Policy here is a
 * real security boundary — it is the only thing standing between the webview
 * and any other origin — so it is built in one place and unit-tested rather
 * than being inlined in a template somewhere.
 */

/** Escape for use inside an HTML attribute value. */
export function escapeAttribute(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Escape for use in HTML text. */
export function escapeHtml(value: string): string {
  return escapeAttribute(value);
}

/**
 * Only an http(s) origin we resolved ourselves may be framed.
 *
 * The URL reaches here from `vscode.env.asExternalUri`, which in a remote or
 * Codespaces window rewrites localhost into a forwarded https host — so this
 * cannot simply hard-code 127.0.0.1. What it CAN do is refuse anything that is
 * not http/https, which keeps `javascript:`, `data:` and `file:` out of both
 * the frame and the CSP that is built from it.
 */
export function frameOriginOf(url: string): string | null {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return null;
  return parsed.origin;
}

/**
 * The page shown in the panel: a full-bleed iframe onto the local server.
 *
 * An iframe rather than re-implementing the UI, because the visualizer is one
 * self-contained page that already talks to this exact server — reproducing
 * any of it here would mean two frontends to keep in step.
 */
/**
 * The policy itself, before it is written into an attribute.
 *
 * Exported so it can be asserted on directly: escaping turns the `'none'`
 * quotes into `&#39;` in the markup, which the browser decodes back before the
 * CSP parser ever sees it — but a test that matched the escaped form would be
 * pinning the escaper rather than the policy.
 *
 * `default-src 'none'` first, then only what the frame actually needs. No
 * script-src at all: this document runs no JavaScript of its own.
 */
export function contentSecurityPolicy(origin: string): string {
  return ["default-src 'none'", `frame-src ${origin}`, "style-src 'unsafe-inline'"].join('; ');
}

export function buildWebviewHtml(url: string): string {
  const origin = frameOriginOf(url);
  if (!origin) throw new Error(`refusing to frame a non-http(s) URL: ${url}`);
  const safeUrl = escapeAttribute(url);
  const csp = contentSecurityPolicy(origin);
  return `<!-- generated by the TreeMap extension; do not edit by hand -->
<meta http-equiv="Content-Security-Policy" content="${escapeAttribute(csp)}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>TreeMap</title>
<style>
  html, body { margin: 0; padding: 0; height: 100%; overflow: hidden; background: var(--vscode-editor-background); }
  iframe { display: block; border: 0; width: 100%; height: 100%; }
</style>
<iframe src="${safeUrl}" title="TreeMap Disk Visualizer" allow="clipboard-write"></iframe>
`;
}

/** The page shown while the server is still coming up, and when it failed. */
export function buildMessageHtml(heading: string, detail: string): string {
  return `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>TreeMap</title>
<style>
  body { margin: 0; height: 100vh; display: flex; flex-direction: column; gap: 8px;
         align-items: center; justify-content: center; text-align: center; padding: 24px;
         font-family: var(--vscode-font-family); color: var(--vscode-foreground);
         background: var(--vscode-editor-background); }
  h1 { font-size: 15px; font-weight: 600; margin: 0; }
  p  { font-size: 13px; margin: 0; max-width: 46ch; line-height: 1.6;
       color: var(--vscode-descriptionForeground); }
</style>
<h1>${escapeHtml(heading)}</h1>
<p>${escapeHtml(detail)}</p>
`;
}
